BibleVerseWebApp/BibleVerseWebApp/Controllers/BibleSearchController.cs
/* CST-247 Enterprise Application Programming III
 * Benchmark
 * BibleSearchController, Version 1
 * Gary Davis
 * 09/08/2019
 * This controller is used to find a verse that the user searched for.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibleVerseWebApp.Models;
using BibleVerseWebApp.Interfaces;
using BibleVerseWebApp.Services;

namespace BibleVerseWebApp.Controllers
{
    public class BibleSearchController : Controller
    {

        //Using DI to get the data from the database
        private readonly IMyBibleRepository verses;

        public BibleSearchController() : this(new BibleRepository())
        { }

        public BibleSearchController(IMyBibleRepository repository)
        {
            verses = repository;
        }

        // GET: BibleSearch
        public ActionResult Index()
        {
            return View();
        }

        //Submit clicked and using LINQ to query the database.
        [HttpPost]
        public ActionResult Index(BIBLE_VERSES verseEntry)
        {
            ViewData["verseTxt"] = "";

            foreach (var i in this.verses.GetBibleVerses())
            {
                if (i.testament == verseEntry.testament && i.book == verseEntry.book && i.chapter == verseEntry.chapter && i.verse == verseEntry.verse)
                {
                    ViewData["verseTxt"] = i.verse_text;
                }
            }
            if (ViewData["verseTxt"].ToString() == "")
            {
                ViewData["verseTxt"] = "Verse not found!";
            }
            return View();
        }
    }
}

BibleVerseWebApp/BibleVerseWebApp/Controllers/SavedVerseController.cs
/* CST-247 Enterprise Application Programming III
 * Benchmark
 * SavedVerseController, Version 1
 * Gary Davis
 * 09/08/2019
 * This controller is used to get a list of the users saved verses.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibleVerseWebApp.Interfaces;
using BibleVerseWebApp.Models;
using BibleVerseWebApp.Services;

namespace BibleVerseWebApp.Controllers
{
    public class SavedVerseController : Controller
    {
        //Using DI to get the data from the database
        private readonly IMyBibleRepository verses;

        public SavedVerseController() : this(new BibleRepository())
        { }

        public SavedVerseController(IMyBibleRepository repository)
        {
            verses = repository;
        }

        // GET: SavedVerse
        public ActionResult Index()
        {
            return View(verses.GetBibleEntry().BIBLE_ENTRY.ToList());
        }
    }
}

BibleVerseWebApp/BibleVerseWebApp/Controllers/VerseLoggerController.cs
/* CST-247 Enterprise Application Programming III
 * Benchmark
 * VerseLoggerController, Version 1
 * Gary Davis
 * 09/08/2019
 * This controller is used to save the users Bible verse.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibleVerseWebApp.Models;
using BibleVerseWebApp.Interfaces;
using BibleVerseWebApp.Services;

namespace BibleVerseWebApp.Controllers
{
    public class VerseLoggerController : Controller
    {
        //Using DI to get the data from the database
        private readonly IMyBibleRepository verses;

        public VerseLoggerController() : this(new BibleRepository())
        { }

        public VerseLoggerController(IMyBibleRepository repository)
        {
            verses = repository;
        }


        // GET: VerseLogger
        public ActionResult Index()
        {
            return View();
        }

        //Save clicked and data is saved to the database
        [HttpPost]
        public ActionResult Index([Bind(Exclude = "Id")]BIBLE_ENTRY verseEntry)
        {
            verses.GetBibleEntry().BIBLE_ENTRY.Add(verseEntry);
            verses.GetBibleEntry().SaveChanges();
            return RedirectToAction("Index", "SavedVerse");
        }
    }
}

BibleVerseWebApp/BibleVerseWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("KJV Bible One Click", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Save-A-Verse", "Index", "VerseLogger")</li>
                    <li>@Html.ActionLink("Your Verses", "Index", "SavedVerse")</li>
                    <li>@Html.ActionLink("KJV Bible Search", "Index", "BibleSearch")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KJV Bible One Click - Gary Davis</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>